window.App={
toast(msg){const t=document.getElementById("toast");t.textContent=msg;t.classList.add("show");clearTimeout(this.tt);this.tt=setTimeout(()=>t.classList.remove("show"),2600)},
openModal(html){document.getElementById("modalContent").innerHTML=html;document.getElementById("modal").classList.remove("hidden")},
closeModal(){document.getElementById("modal").classList.add("hidden")},
escape(s){return String(s).replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))},
toggleTheme(){const next=document.body.dataset.theme==="dark"?"light":"dark";document.body.dataset.theme=next;localStorage.setItem("theme",next)},
right(){document.getElementById("rightbar").innerHTML=`<div class="widget"><div class="widget-title">📅 Próximos eventos</div><div class="side-item"><div class="avatar sm">📝</div><div><b>Prova de Matemática</b><small>20 de agosto · 08:00</small></div></div><div class="side-item"><div class="avatar sm">⚽</div><div><b>Interclasses</b><small>28 de agosto</small></div></div></div>${Achievements.renderSide()}<div class="widget"><div class="widget-title">🛡️ Segurança</div><p style="font-size:12px;color:var(--muted);line-height:1.5">Denúncias podem sinalizar spam, assédio e conteúdo proibido. Banimentos definitivos devem passar por revisão.</p></div>`},
render(){Posts.render();Groups.render();Calendar.render();Notifications.render();Profile.render();Admin.render();this.right();},
init(){document.body.dataset.theme=localStorage.getItem("theme")||"light";document.querySelectorAll(".nav-btn").forEach(b=>b.onclick=()=>{document.querySelectorAll(".nav-btn").forEach(x=>x.classList.remove("active"));b.classList.add("active");document.querySelectorAll(".page").forEach(p=>p.classList.remove("active"));document.getElementById(b.dataset.page).classList.add("active")});document.getElementById("googleLogin").onclick=()=>Auth.loginGoogle();document.getElementById("demoLogin").onclick=()=>Auth.loginDemo();if(localStorage.getItem("conecta_logged"))Auth.refresh();this.render()}
};
App.init();