window.Groups={data:[
{id:1,name:"9º Ano — Geral",type:"Público",desc:"Discussões e avisos da turma.",members:32},
{id:2,name:"Fofocas da Escola 👀",type:"Público",desc:"Converse, mas respeite as regras.",members:104},
{id:3,name:"Matemática",type:"Privado",desc:"Exercícios, dúvidas e estudos.",members:18},
{id:4,name:"Grêmio Estudantil",type:"Público",desc:"Projetos, reuniões e eventos.",members:47}],
render(){document.getElementById("groups").innerHTML=`<div class="topbar"><h1>Grupos</h1><button class="btn primary" onclick="Groups.create()">+ Criar</button></div><input id="groupSearch" class="search" placeholder="Buscar grupos..." oninput="Groups.list()"><div id="groupGrid" class="grid"></div>`;this.list()},
list(){const q=(document.getElementById("groupSearch")?.value||"").toLowerCase();document.getElementById("groupGrid").innerHTML=this.data.filter(g=>g.name.toLowerCase().includes(q)).map(g=>`<div class="card group-card"><span class="badge">${g.type}</span><h3>${g.name}</h3><p>${g.desc}</p><div class="member-list"><div class="avatar">A</div><div class="avatar">B</div><div class="avatar">C</div></div><p>${g.members} membros</p><br><button class="secondary" onclick="Members.join(${g.id})">${g.type==="Privado"?"Solicitar entrada":"Entrar no grupo"}</button> <button class="secondary" onclick="Groups.open(${g.id})">Ver</button></div>`).join("")},
create(){App.openModal(`<h2>Criar grupo</h2><input id="gName" class="search" placeholder="Nome"><input id="gDesc" class="search" placeholder="Descrição"><select id="gType" class="search"><option>Público</option><option>Privado</option></select><div style="text-align:right"><button class="secondary" onclick="App.closeModal()">Cancelar</button> <button class="btn primary" onclick="Groups.save()">Criar</button></div>`)},
save(){const n=document.getElementById("gName").value.trim();if(!n)return App.toast("Informe um nome.");this.data.push({id:Date.now(),name:n,type:document.getElementById("gType").value,desc:document.getElementById("gDesc").value||"Novo grupo escolar.",members:1});App.closeModal();this.list();App.toast("Grupo criado.")},
open(id){const g=this.data.find(x=>x.id===id);App.openModal(`<h2>${g.name}</h2><p>${g.desc}</p><div class="group-chat"><div class="message">Bem-vindos ao grupo!</div><div class="message me">Vamos organizar as próximas atividades.</div></div><input id="groupMsg" class="search" placeholder="Mensagem"><button class="btn primary" onclick="App.toast('Mensagem enviada!')">Enviar</button>`)}
};